config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: "users/omniauth_callbacks",
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :categories, only: [:show] do
  end

  resources :projects, except: [:index] do   #collection的網址 => projects/owner
    collection do
      get :owner
      patch :owner, action: :owner_update
      get :search
    end
    member do
      resources :project_supports, param: :project_support_id, except: [:index, :show, :edit, :new] do  #member的網址 => projects/1/project_supports
      end
    end
  end

  resources :pledges, only: [:index, :show, :create] do
  end

  resources :payments do
    collection do
      get :mpg
      get :canceled
      post :notify
      post :paid
      post :not_paid_yet
    end
  end

end

app/models/pledge.rb
class Pledge < ApplicationRecord
  belongs_to :user
  belongs_to :project_support

  has_one :payment
  has_one :project, through: :project_support

  enum status: [:not_selected_yet, :not_paid, :paid, :canceled]

  validates :project_name, :support_name, presence: true
  validates_numericality_of :support_price, greater_than_or_equal_to: 0
  validates_numericality_of :quantity, greater_than_or_equal_to: 1
  validate :is_user_project_owner?

  def end_price
    support_price * quantity
  end

  def paid!
    self.issue_date = Time.now
    super

    project.update_status_if_reaching_goal!
  end

  def status_to_string
    case status_before_type_cast  #取得 enum 的值
    when Pledge.statuses[:not_selected_yet]
      return "未選擇"
    when Pledge.statuses[:not_paid]
      return "未付款"
    when Pledge.statuses[:paid]
      return "已付款"
    when Pledge.statuses[:canceled]
      return "已取消"
    else
      return "狀態未明"
    end
  end

  private

  def is_user_project_owner?
    if project_support.project.project_owner.user == user
      errors.add(:user, "不可以投資自己的專案")
    end
  end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  #可以想成是Order 訂單頁面， 只是換一個名稱
  # 募資網站 -> 贊助 Pledge
  # 購物網站 -> 訂單 Order

  before_action :is_login?
  before_action :get_project_support, only: [:create]
  before_action :get_pledge, except: [:create, :index]


  def index
    @pledges = current_user.valided_pledges
  end

  def show
    case @pledge.status_before_type_cast
    when Pledge.statuses[:paid]
      render "paid"
    when Pledge.statuses[:not_paid]
      render "not_paid"
    else
      flash[:alert] = "沒有此贊助"
      redirect_to root_path
      return
    end
  end

  def create
    @pledge = Pledge.create({
                              user: current_user,
                              project_support: @project_support,
                              project_name: @project_support.project.name,
                              support_name: @project_support.name,
                              support_price: @project_support.price,
                              quantity: params[:quantity]
                            })
    redirect_to mpg_payments_path(pledge_id: @pledge.id)
  end

  private

  def is_login?
    unless current_user
      flash[:error] = "您尚未登入"
      redirect_to user_session_path  #login_path
      return
    end
  end

  def get_project_support
    @project_support = ProjectSupport.is_published.find_by_id(params[:id])

    unless @project_support
      flash[:alert] = "沒有此贊助方案"
      redirect_to root_path
      return
    end
  end

  def get_pledge
    @pledge = Pledge.find_by(id: params[:id], user: current_user)

    unless @pledge
      flash[:alert] = "沒有此贊助"
      redirect_to root_path
      return
    end
  end

end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/views/pledges/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div style="margin: 32px auto;">
        <h3>我的贊助:</h3>
        <br/>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">贊助</th>
              <th scope="col">方案</th>
              <th scope="col">價格</th>
              <th scope="col">狀態</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @pledges.each_with_index do |pledge, index| %>
              <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= pledge.project_name %></td>
                <td><%= pledge.support_name %></td>
                <td><%= pledge.payment.try(:end_price) %></td>
                <td><%= pledge.status_to_string %></td>
                <td><%= link_to '查看', pledge_path(pledge) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/pledges/not_paid.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div style="margin: 32px auto;">
        <p>尚未付款</p>
        <h3><%= @pledge.project_name %></h3>
        <p>方案: <%= @pledge.support_name %></p>
        <p>單號: <%= @pledge.merchantOrderNo %></p>
        <p>單價: <%= @pledge.support_price %></p>
        <p>數量: <%= @pledge.quantity %></p>
        <p>總價: <%= @pledge.payment.end_price %></p>
        <p>
          贊助內容:
        </p>
        <p>
          <%= @pledge.project_support.description %>
        </p>
        <hr/>
        <p> 付款資訊 </p>
        <% case @pledge.payment.payment_type_before_type_cast %>
        <% when Payment.payment_types[:cvs] %>
          <p>繳費代碼: <%= @pledge.payment.code_no %></p>
          <p>付款截止日: <%= @pledge.payment.unpaid_payment_expire_date %></p>
        <% end %>
        <hr/>
        <%= link_to "回到首頁", root_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/pledges/paid.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div style="margin: 32px auto;">
        <p>已贊助</p>
        <h3><%= @pledge.project_name %></h3>
        <p>方案: <%= @pledge.support_name %></p>
        <p>單號: <%= @pledge.merchantOrderNo %></p>
        <p>單價: <%= @pledge.support_price %></p>
        <p>數量: <%= @pledge.quantity %></p>
        <p>總價: <%= @pledge.payment.end_price %></p>
        <p>生效日: <%= @pledge.issue_date %></p>
        <p>
          贊助內容:
        </p>
        <p>
          <%= @pledge.project_support.description %>
        </p>
        <hr/>
        <p> 付款資訊 </p>

        <hr/>
        <%= link_to "回到首頁", root_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>