config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: "users/omniauth_callbacks",
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :categories, only: [:show] do
  end

  resources :projects, except: [:index] do   #collection的網址 => projects/owner
    collection do
      get :owner
      patch :owner, action: :owner_update
      get :search
    end
    member do
      resources :project_supports, param: :project_support_id, except: [:index, :show, :edit, :new] do  #member的網址 => projects/1/project_supports
      end
    end
  end

  resources :pledges, only: [:index, :show, :create] do
  end

  resources :payments do
    collection do
      get :mpg
      get :canceled
      post :notify
      post :paid
      post :not_paid_yet
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :project_owner
  belongs_to :category

  has_one :user, through: :project_owner
  has_many :project_supports
  has_many :pledges, through: :project_supports
  has_many :paid_pledges, through: :project_supports

  enum status: [:is_hidden, :is_published, :succeeded, :failed, :cancel]

  scope :is_now_on_sale, -> {self.where(status: [:is_published, :succeeded]).where('due_date > ?', Time.now)}

  scope :succeeded_and_done, -> {self.succeeded.where('due_date < ?', Time.now)}

  scope :past_projects, -> {Project.where.not(status: [:cancel, :is_hidden]).where('due_date < ?', Time.now)}

  mount_uploader :cover_image, CoverImageUploader


  validates :name, :brief, :description, :ad_url, :cover_image, presence: true
  validates_numericality_of :goal, greater_than: 0
  validate :valid_due_date?

  def paid_pledges_amounts
    # sum = 0
    # paid_pledges.each |pledge| do
    #  sum += pledge.support_price * pledge.quantity
    # end
    # return sum    這個寫法等於下面的寫法

    return paid_pledges.inject(0) do |sum, pledge|
      sum += pledge.support_price * pledge.quantity
    end
  end

  def percentage_of_reaching_goal
    paid_pledges_amounts.to_f / goal.to_f
  end

  def update_status_if_reaching_goal!
    if self.is_published? && (self.percentage_of_reaching_goal.to_i >= 1)
      self.succeeded!
    end
  end

  def status_to_string
    case status_before_type_cast  #取得 enum 的值
    when Project.statuses[:is_hidden]
      return "尚未開始"
    when Project.statuses[:is_published]
      return "募資中"
    when Project.statuses[:succeeded]
      return "募資已成功"
    when Project.statuses[:failed]
      return "募資失敗"
    when Project.statuses[:cancel]
      return "募資已取消"
    else
      return "狀態未明"
    end
  end

  def seconds_left
    due_date.to_i - Time.now.to_i
  end

  private

  def valid_due_date?
    if due_date.blank? || due_date < ((created_at || Time.zone.now) + 7.days)
        errors.add(:due_date, "due_date is not correct")
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :is_login?, except: [:show, :search]
  before_action :get_project, only: [:show]
  before_action :get_project_for_update, only: [:edit, :update, :destroy]

  def show
    @due_date = @project.due_date
    @project_supports = @project.project_supports
    @percentage = (@project.percentage_of_reaching_goal * 100).round(2)
  end

  def new
    @project = Project.new
    @categories = Category.is_published
  end

  def create
    @project = Project.create(project_permit.merge(project_owner: current_user.project_owner))

    if @project.valid?
      redirect_to edit_project_path(@project)
    else
      flash[:alert] = @project.errors.messages.map{|k,v| "#{t(k)}: #{v[0]}" }
      redirect_to new_project_path
    end
  end

  def edit
    @project_supports = @project.project_supports
    @new_project_support = ProjectSupport.new
    @first_project_support = @project_supports.first

    unless @first_project_support
      @project_support = ProjectSupport.create(
                            project: @project,
                            name: "未命名",
                            description: "未填寫",
                            price: 0
                          )
    end
  end

  def update
    if @project.update(project_permit)
      flash[:notice] = "更新成功"
    else
      flash[:alert] = @project.errors.messages.map{|k,v| "#{t(k)}: #{v[0]}" }
    end

    redirect_to edit_project_path(@project)
  end

  def destroy
    if @project.pledges.count > 0
      flash[:alert] = "募資專案: #{@project.name} 已經有人贊助，無法刪除"
    else
      @project.cancel!
      flash[:notice] = "募資專案: #{@project.name} 已經被刪除"
    end

    redirect_to owner_projects_path
  end

  def owner
    @project_owner = current_user.project_owner

    @projects = @project_owner.projects.where.not(status: [:cancel])
  end

  def owner_update
    @project_owner = current_user.project_owner
    @project_owner.update(project_owner_permit)

    redirect_to action: :owner
  end

  def search
    @key_words = params[:keyWord]
    if @key_words
      word = "%#{@key_words}%"
      @projects = Project.eager_load(:user).is_now_on_sale.where("projects.name LIKE ? or brief LIKE ? or users.name Like ?",word, word, word)
    else
      @projects = []
    end
  end

  private

  def get_project
    @project = Project.is_now_on_sale.find_by_id(params[:id])

    unless @project
      flash[:alert] = "沒有這個募資專案"
      redirect_to root_path
    end
  end

  def get_project_for_update
    @project = Project.find_by(id: params[:id], project_owner: current_user.project_owner)

    unless @project
      flash[:alert] = "沒有這個募資專案"
      redirect_to root_path
      return
    end
  end

  def is_login?
    unless  current_user
      flash[:error] = "您尚未登入"
      redirect_to user_session_path
      return
    end
  end

  def project_owner_permit
    params.require(:project_owner).permit([:description, :cover_image])
  end

  def project_permit
    params.require(:project).permit([:name, :category_id, :brief, :description, :cover_image, :ad_url, :goal, :due_date, :status])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_card.html.erb
<% percentage = (project.percentage_of_reaching_goal * 100).round(2) %>

<%= link_to project_path(project), style: "text-decoration: none; color: black;" do %>
<div class="card" style="width: 100%; margin: 32px auto;">
  <%= image_tag project.cover_image.url, class: "card-img-top" %>
  <div class="card-body">
    <h5 class="card-title">
      <%= project.name %>
    </h5>
    <div class="card-text">
      <p><%= project.brief %></p>
      <p style="color: red;" class="seconds_countdown" data-seconds="<%= project.seconds_left %>"></p>
      <p><b><%= project.status_to_string %></b></p>
      <p>已募得:
        <span style="color: red;">
          <%= project.paid_pledges_amounts %>
        </span>
        <span>/</span>
        <sub><%= project.goal %></sub>
      </p>
      <div class="progress">
        <div class="progress-bar bg-info" role="progressbar" style="width: <%= "#{percentage}%" %>;" aria-valuenow="<%= percentage %>" aria-valuemin="0" aria-valuemax="100">
          <% unless percentage == 0.0  %>
            <%= "#{percentage}%" %>
          <% end %>
        </div>
      </div>
      <br/>
      <p>已經有 <%= project.pledges.count %> 個人贊助</p>
    </div>
  </div>
</div>
<% end %>

app/views/projects/_card_list.html.erb
 <div class="row">
    <% projects.each do |project| %>
      <div  class="col-12 col-sm-6 col-md-4">
        <%= render 'projects/card', project: project %>
      </div>
    <% end %>
 </div>

app/views/projects/_show_detail_tabs.html.erb
<hr/>
<div style="line-height: 2;">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#description" role="tab" aria-controls="home" aria-selected="true">產品敘述</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab"  href="#profile" role="tab" aria-controls="profile" aria-selected="false">募資團隊</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="contact-tab" data-toggle="tab" href="#spec" role="tab" aria-controls="contact" aria-selected="false">產品規格</a>
    </li>
  </ul>
</div>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="home-tab">
    <section style="margin: 32px auto;">
      <%= @project.description %>
    </section>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <section style="margin: 32px auto;">
      <%= image_tag (@project.project_owner.cover_image_url || "https://via.placeholder.com/350x200"), size: "300x200", id: "target", original_url: @project.project_owner.cover_image_url %>
      <br/>
      <br/>
      <%= @project.project_owner.description %>
    </section>
  </div>
  <div class="tab-pane fade" id="spec" role="tabpanel" aria-labelledby="contact-tab">
    <section style="margin: 32px auto;">
      目前沒有欄位
    </section>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class='row'>
    <div class='col-12'>
      <div style="padding: 32px 0;">
        <h3>修改專案</h3>
        <br/>
        <%= form_for @project do |f| %>
          <%= f.label "上架狀態"%><br/>
          <%= f.select :status, Project.statuses.keys.map { |s| [s.humanize, s] }, {include_blank: true}, {class: "form-control"} %>
          <br/>
          <%= f.label :name, "專案名稱" %><br/>
          <%= f.text_field :name, class: "form-control" %>
          <br/>
          <%= f.label :category_id, "類別" %><br/>
          <%= f.select :category_id, @categories.collect { |p| [ p.name, p.id ] }, {include_blank: true}, {class: "form-control"} %>
          <br/>
          <%= f.label :brief, "簡介" %><br/>
          <%= f.text_field :brief, class: "form-control" %>
          <br/>
          <%= f.label :description, "完整敘述" %><br/>
          <%= f.text_area :description, class: "form-control", size: "30x10" %>
          <br/>
          <%= f.label :goal, "目標金額" %><br/>
          <%= f.number_field :goal, min: 0, class: "form-control" %>
          <br/>
          <%= f.label :due_date, "截止日期" %><br/>
          <%= f.date_field :due_date, class: "form-control" %>
          <br/>
          <%= f.label :ad_url, "廣告影片網址" %><br/>
          <%= f.text_field :ad_url, class: "form-control" %>
          <br/>
          <%= f.label :cover_image, "圖片" %><br/>
          <%= image_tag (@project.cover_image_url || "https://via.placeholder.com/350x200"), size: "300x200", id: "target", original_url: @project.cover_image_url %>
          <br/>
          <%= f.file_field :cover_image, class: "btn btn-default" %>
          <br />
          <hr/>
          <%= f.submit "確定修改", class: "btn btn-warning" %>
          <%= link_to "取消", owner_projects_path(), class: "btn btn-default"%>
        <% end %>
      </div>
    </div>
    <div class='col-12'>
      <div style="margin: 32px auto;">
        <div class="clearfix">
          <h3 class="float-left">所有贊助方案：</h3>
          <%= form_for @new_project_support do |f| %>
            <%= f.submit "新增", class: "btn btn-info float-right" %>
          <% end %>
        </div>
        <br/>
        <table class="table table-striped">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">名稱</th>
            <th scope="col">價錢</th>
            <th scope="col">敘述</th>
            <th scope="col">狀態</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          <% @project_supports.each_with_index do |support, index|%>
            <tr>
              <th scope="row"><%= index + 1%></th>
              <td><%= support.name %></td>
              <td><%= support.price %></td>
              <td><%= support.description %></td>
              <td><%= support.status_to_string %></td>
              <td><a class="project_support_edit_button" href="javascript:void(0);" data-toggle="modal" data-target="#edit_project_support" data-detail="<%= support.to_json %>">編輯</a></td>
              <td><%= link_to '刪除', project_support_path(project_support_id: support.id), method: :delete, data: { confirm: '你確定要刪除嗎?' } %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div id="edit_project_support" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="padding: 48px 16px;">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <%= form_for @first_project_support, url: project_support_path(project_support_id: @first_project_support.id), html: {id: "project_support_edit_form"} do |f| %>
              <%= f.label :name, "贊助名稱" %><br/>
              <%= f.text_field :name, class: "form-control" %>
              <br/>
              <%= f.label :description, "完整敘述" %><br/>
              <%= f.text_area :description, class: "form-control", size: "30x10" %>
              <%= f.label :price, "贊助金額" %><br/>
              <%= f.number_field :price, min: 0, class: "form-control" %>
              <br/>
              <%= f.label "上架狀態"%><br/>
              <%= f.select :status, ProjectSupport.statuses.keys.map { |s| [s.humanize, s] }, {include_blank: true}, {class: "form-control"} %>
              <br/>
              <%= f.submit "修改", class: "btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
    $(function(){
        $("#project_cover_image").change(function(){
            readURL(this, "target");
        });

        function readURL(input, image_tag_id){
            if(input.files && input.files[0]){
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#" + image_tag_id).attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }else{
                var original_url = $("#" + image_tag_id).attr("original_url");
                $("#" + image_tag_id).attr('src', original_url);
            }
        }

        $(".project_support_edit_button").click(function(){
            var detail = $(this).data("detail");

            var newURL = "/projects/"+ <%= @project.id %> +"/project_supports/" + detail.id;
            $("#project_support_edit_form").attr("action", newURL);
            $("#project_support_name").val(detail.name);
            $("#project_support_description").val(detail.description);
            $("#project_support_price").val(detail.price);
            $("#project_support_status").val(detail.status);
        })

    });
</script>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div style="padding: 32px 0;">
        <h3>新增專案</h3>
        <br/>
        <%= form_for @project do |f| %>
          <%= f.label :name, "專案名稱" %><br/>
          <%= f.text_field :name, class: "form-control" %>
          <br/>
          <%= f.label :category_id, "類別" %><br/>
          <%= f.select :category_id, @categories.collect { |c| [c.name, c.id] }, {inclued_blank: true}, {class: "form-control"} %>
          <br/>
          <%= f.label :brief, "簡介" %><br/>
          <%= f.text_field :brief, class: "form-control"%>
          <br/>
          <%= f.label :description, "完整敘述" %><br/>
          <%= f.text_area :description, class: "form-control", size: "30x10" %>
          <br/>
          <%= f.label :goal, "目標金額" %><br/>
          <%= f.number_field :goal, min: 0, class: "form-control" %>
          <br/>
          <%= f.label :due_date, "截止日期" %><br/>
          <%= f.date_field :due_date, class: "form-control" %>
          <br/>
          <%= f.label :ad_url, "廣告影片網址" %><br/>
          <%= f.text_field :ad_url, class: "form-control" %>
          <br/>
          <%= f.label :cover_image, "圖片" %><br/>
          <%= image_tag (@project.cover_image_url || "https://via.placeholder.com/350x200"), size: "300x200", id: "target", original_url: @project.cover_image_url %>
          <br/>
          <%= f.file_field :cover_image, class: "btn btn-default" %>
          <br/>
          <hr/>
          <%= f.submit "送出", class: "btn btn-info" %>
          <%= link_to "取消", owner_projects_path, class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    $(function(){
        $("#project_cover_image").change(function(){
            readURL(this, "target");
        });

        function readURL(input, image_tag_id){
            if(input.files && input.files[0]){
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#" + image_tag_id).attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }else{
                var original_url = $("#" + image_tag_id).attr("original_url");
                $("#" + image_tag_id).attr('src', original_url);
            }
        }
    });
</script>

app/views/projects/owner.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <nav style="margin: 48px;">
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <a class="nav-link active" id="nav-home-tab" data-toggle="tab" href="#project-list" role="tab" aria-controls="nav-home" aria-selected="true">所有專案</a>
          <a class="nav-link" id="nav-profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="nav-profile" aria-selected="false">團隊設定</a>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="project-list" role="tabpanel" aria-labelledby="nav-home-tab" style="min-height: 800px;">
          <div style="margin: 32px auto;">
            <h3>所有募資專案:</h3>
            <div class="clearfix">
              <%= link_to '新增', new_project_path, class: "btn btn-info float-right" %>
            </div>
            <br/>
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">名稱</th>
                  <th scope="col">敘述</th>
                  <th scope="col">結束日期</th>
                  <th scope="col">狀態</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                <% @projects.each_with_index do |project, index| %>
                  <tr>
                    <th scope="row"><%= index + 1 %></th>
                    <td><%= project.name %></td>
                    <td><%= project.brief %></td>
                    <td><%= project.due_date %></td>
                    <td><%= project.status_to_string %></td>
                    <td><%= link_to '修改', edit_project_path(project) %></td>
                    <td><%= link_to '刪除', project_path(project), method: :delete, data: { confirm: '你確定要刪除嗎?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="nav-profile-tab" style="min-height: 800px;">
          <!-- 募資團隊設定 start -->
          <div style="margin: 32px auto;">
            <h3>募資團隊設定：</h3>
            <br/>
            <%= form_for @project_owner, url: owner_projects_path, method: :patch do |f|%>
              <%= f.label :description, "敘述" %><br/>
              <%= f.text_area :description, class: "form-control" %><br />

              <%= f.label :cover_image, "圖片" %><br/>
              <%= image_tag (@project_owner.cover_image_url || "https://via.placeholder.com/350x200"), size: "300x200", id: "target", original_url: @project_owner.cover_image_url %>
              <br/>
              <%= f.file_field :cover_image, class: "btn btn-default" %>
              <br />
              <br />
              <hr/>
              <%= f.submit "確認修改", class: "btn btn-info" %>
            <% end %>
          </div>
          <!-- 募資團隊設定 end -->
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $(function(){
        $("#project_owner_cover_image").change(function(){
            readURL(this, "target");
        });

        function readURL(input, image_tag_id){
            if(input.files && input.files[0]){
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#" + image_tag_id).attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }else{
                var original_url = $("#" + image_tag_id).attr("original_url");
                $("#" + image_tag_id).attr('src', original_url);
            }
        }
    });
</script>

app/views/projects/search.html.erb
<div id="projects_search" style="margin: 56px 0;">
  <div class="container">
    <h3>搜尋: <%= @key_words %></h3>
  </div>
  <div class="container">
    <% unless @projects.blank? %>
      <%= render 'projects/card_list', projects: @projects %>
    <% else %>
      <div class="col-12">
        <p>沒有搜尋到結果</p>
      </div>
    <% end %>
    <hr/>
  </div>
</div>

app/views/projects/show.html.erb
<div id="project_show" style="margin: 58px auto;">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-8">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="<%= @project.ad_url %>"></iframe>
        </div>
      </div>
      <div class="col-12 col-md-4">
        <div class="card" style="width: 100%;">
          <div class="card-body">
            <h5 class="card-title">
              <%= @project.name %>
            </h5>
            <div class="card-text">
              <p><b>已募得金額</b></p>
              <h2 style="color: red;">
                NT$ <%= @project.paid_pledges_amounts %>
              </h2>
              <h5>贊助目標: NT$ <%= @project.goal %></h5>
              <br/>
              <p style="color: red;" class="seconds_countdown" data-seconds="<%= @project.seconds_left %>"></p>
              <p><b><%= @project.status_to_string %></b></p>
              <div class="progress">
                <div class="progress-bar bg-info" role="progressbar" style="width: <%= "#{@percentage}%" %>;" aria-valuenow="<%= @percentage %>" aria-valuemin="0" aria-valuemax="100">
                  <% unless @percentage == 0.0  %>
                    <%= "#{@percentage}%" %>
                  <% end %>
                </div>
              </div>
              <br/>
              <p>已經有 <%= @project.pledges.count %> 個人贊助 </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div style="margin: 32px auto;">
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-8">
          <%= render 'projects/show_detail_tabs', project: @project %>
        </div>
        <div class="col-12 col-md-4">
          <% @project_supports.each do |project_support| %>
            <section>
              <%= form_tag pledges_path, method: :post do %>
                <h3><%= project_support.name %></h3>
                <h5><%= project_support.price %> / 每單位</h5>
                <div>
                  <%= project_support.description %>
                </div>
                <input type="hidden" name="id" value="<%= project_support.id %>">

                <div class="form-group">
                  <label for="quantity">贊助數量</label>
                  <input type="number" class="form-control" id="quantity" name="quantity" placeholder="1 ~ 10" max="10" min="1" value="1">
                </div>
                <div class="clearfix">
                  <button type="submit" class="btn btn-info float-right">贊助</button>
                </div>
              <% end %>
              <hr/>
            </section>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>