config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: "users/omniauth_callbacks",
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :categories, only: [:show] do
  end

  resources :projects, except: [:index] do   #collection的網址 => projects/owner
    collection do
      get :owner
      patch :owner, action: :owner_update
      get :search
    end
    member do
      resources :project_supports, param: :project_support_id, except: [:index, :show, :edit, :new] do  #member的網址 => projects/1/project_supports
      end
    end
  end

  resources :pledges, only: [:index, :show, :create] do
  end

  resources :payments do
    collection do
      get :mpg
      get :canceled
      post :notify
      post :paid
      post :not_paid_yet
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="container-fluid" style="height: 300px;background-color: black;">
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">進度條Rails課程</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class=" mr-auto">
    </div>
    <%= form_tag search_projects_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
      <input class="form-control mr-sm-2" type="search" placeholder="搜尋專案" aria-label="Search" name="keyWord">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜尋</button>
    <% end %>
    <ul class="navbar-nav ml-sm-2">
      <% if @categories %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            類別
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% @categories.each do |category| %>
              <%= link_to category.name, category_path(category), class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      <% end %>
      <li class="nav-item">
        <% if current_user %>
          <%= link_to '我想募資', owner_projects_path, class: "nav-link"  %>
        <% else%>
          <%= link_to '我想募資', user_session_path, class: "nav-link"%>
        <% end %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to '我的贊助', pledges_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <% if current_user %>
          <%= link_to '登出', destroy_user_session_path, method: :delete, class: "nav-link"  %>
        <% else%>
          <%= link_to '登入', user_session_path, class: "nav-link"%>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
      進度條腳踏發動器
    </title>
    <meta name="description" content="這是進度條線上課程Ruby on Rails與Bootstrap 4課程範例，僅供測試與學習使用，請勿當真" />
    <meta name="keywords" content="Bootstrap, 網站, 開發, 程式, 設計, 教學, jquery, HTML, HTML5, CSS, JavaScript, Swift, WordPress, iOS, Ruby On Rails, Arduino">
    <meta name="copyright" content="思誠科技有限公司">
    <meta name="robots" content="NOINDEX, NOFOLLOW">
    <meta name="reply-to" content="service@progressbar.tw">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= javascript_include_tag 'application'%>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <script>
        $(function (){
            countdown();
            setInterval("countdown()", 1000);
        })
    </script>

  </head>

  <body>
  <%= render partial: 'layouts/nav'%>
  <%= render partial: 'layouts/notice'%>
  <%= yield %>
  <%= render partial: 'layouts/footer'%>
  </body>
</html>